### ISSUE TITLE
Displays "This app is not genuine"

### ISSUE THREAD

**Issue by katat** [obsidiansystems/ledger-app-nervos#162]
When the ckb app is opened on device, it displays "This app is not genuine". I guess this is expected since the app is not yet officially accepted by Ledger?

**Comment by mikereinhart** [comment]
This happens whenever you 'sideload' an application, meaning you load it *without* Ledger Live. This is because Ledger signs the apps in the store. We'll add a note about this to our documentation!

**Comment by mikereinhart** [comment]
I've added a note to our docs about this https://github.com/obsidiansystems/ledger-app-nervos/blob/develop/README.md#command-line-installations-this-app-is-not-genuine

Closing this issue for that reason, thanks for mentioning, @katat!
