### ISSUE TITLE
CKB address display on device

### ISSUE THREAD

**Issue by katat** [obsidiansystems/ledger-app-nervos#163]
The CKB addresses displayed on device are all mainnet based even the operations, such as  `getWalletPublicKey` and `signTransaction`, targets the testnet.

For example, when signing a transaction for testnet, the device prompts a mainnet destination address. I think this would be confusing to the users. Can we get the information prompted by the ckb app to be consistent with the targeted network?

**Comment by mikereinhart** [comment]
Hi @katat - there is a configuration in the app where you can change the display of the address between mainnet (ckb) and testnet (ckt). Let us know if you're unable to find it or it doesn't behave as expected!

**Comment by mikereinhart** [comment]
I've done a quick scan of our documentation related to this, and the closest reference is found here - https://github.com/obsidiansystems/ledger-app-nervos#obtain--verify-public-key

**Comment by katat** [comment]
I see. Thanks @mikereinhart
