### ISSUE TITLE
Update logo for nervos app

### ISSUE THREAD

**Issue by katat** [obsidiansystems/ledger-app-nervos#203]
Hi there,

Since Nervos has updated its suite of logos, including the CKB symbol logo, we will need to update the logo of the ledger as well. The attached zip file contains the updated logos.

I had a try to update the icons in this [folder](https://github.com/obsidiansystems/ledger-app-nervos/tree/master/icons) and install the update app following the [instruction](https://github.com/obsidiansystems/ledger-app-nervos/#installing-the-ledger-application-from-source) on ubuntu 20.04.1, but the build/install command `./nix/install.sh -t s` is not able to go beyond as the screenshot shown below:
<img width="1017" alt="Screen Shot 2020-12-28 at 2 20 16 PM" src="https://user-images.githubusercontent.com/1587352/103193576-d154c080-4917-11eb-84b4-de6e9cb09463.png">

Without being able to verify it on my own device, I am not sure if simply replacing the icons in the folder works. Would you please help take a look at this and update the new logo onto Ledger?

[Nervos icons for Ledger.zip](https://github.com/obsidiansystems/ledger-app-nervos/files/5746076/Nervos.icons.for.Ledger.zip)

**Comment by ApolloUnicorn** [comment]
@katat are you working from a branch that we can look at?

**Comment by katat** [comment]
Hi @ApolloUnicorn 

Here is a PR to update the icons https://github.com/obsidiansystems/ledger-app-nervos/pull/204
But I haven't been able to verify if it works. Appreciated if you can help take a look.

Thanks

**Comment by ApolloUnicorn** [comment]
@katat our QA team was able to load the app from that commit (pulling from your repo actually). It loaded on the device and I'm including a paste of the output. Unfortunately the logo did not come across the way I guessing you would like. 

https://pastebin.com/t8Txakvh

![Nervos](https://user-images.githubusercontent.com/53824963/103300428-76c56e00-49c4-11eb-99de-7e4a0fb3e97c.png)
![IMG_5040](https://user-images.githubusercontent.com/53824963/103300455-83e25d00-49c4-11eb-9eec-51e5eba7e878.JPG)

**Comment by ApolloUnicorn** [comment]
For context, the Nano X logo is showing correctly. That one should remain unchanged.
![image](https://user-images.githubusercontent.com/53824963/103302629-b6db1f80-49c9-11eb-9e4c-7f2b27eb3a80.jpg)

**Comment by katat** [comment]
Thanks @ApolloUnicorn 
I have updated the icon of nano s to 16px and the PR to target the develop branch.

**Comment by ApolloUnicorn** [comment]
@katat I can't push commits because of repo access. Could you please add this logo as the nano-s-nervos.gif? When I looked at the pixel level preview of your last commit it showed gradients which the app cannot process.
![nano-s-nervos](https://user-images.githubusercontent.com/53824963/103676332-f2886300-4f4e-11eb-935b-652b4f4586be.gif)

**Comment by ApolloUnicorn** [comment]
![nano-s-nervos](https://user-images.githubusercontent.com/53824963/103676332-f2886300-4f4e-11eb-935b-652b4f4586be.gif)

**Comment by ApolloUnicorn** [comment]
Documenting the before and after of my logo changes
**_Before_**
<img width="711" alt="Screen Shot 2021-01-05 at 12 12 57 PM" src="https://user-images.githubusercontent.com/53824963/103676957-ba355480-4f4f-11eb-8231-ab44b3653b4d.png">
<img width="899" alt="Screen Shot 2021-01-05 at 12 13 48 PM" src="https://user-images.githubusercontent.com/53824963/103676965-bbff1800-4f4f-11eb-9950-8ae95c149f57.png">
**_After_**
<img width="686" alt="Screen Shot 2021-01-05 at 12 14 47 PM" src="https://user-images.githubusercontent.com/53824963/103676970-bd304500-4f4f-11eb-95d9-37e2cd0f29ea.png">

**Comment by katat** [comment]
Awesome @ApolloUnicorn 
I have included this gif file you shared and pushed a new commit to the PR.

**Comment by ApolloUnicorn** [comment]
@katat for some reason there was still an issue so I made a new branch from my end. See results commented there.
https://github.com/obsidiansystems/ledger-app-nervos/pull/205

**Comment by katat** [comment]
Thanks @ApolloUnicorn
